export const publi1 = {
  id: 1,
  titulo: "Vendo casa en jardín loma alta, Santa Ana",
  desc: "Vendo casa en buen estado, 5 años de construcción, bajo terreno firme y con los papeles en regla, el motivo de la venta es para poder conseguir una casa en Costa Rica, motivos de mudanza, precio fijo, aunque poco negociable",
  precio: 240000,
  extension: 140,
  departamento: "Santa Ana",
  municipio: "Santa Ana Central",
  localidad: "Loma Alta",
  referencia: "A unos 4 casas de la ferreteria el perro",
  usuario: 1234,
  cantimg: 3,
  habita: 6,
  bano: 4,
  garage: 2,
  patio: 2,
};
export const publi2 = {
  id: 2,
  titulo: "Vendo casa en la campanera, solo interesados, sean serios",
  desc: "Vendo casa en buena bonita y barata, no se que tiene pero no funciona el agua, inundada, lo que ven es, el precio es fijo, no sean mañosos, lo quiero vender porque necesito vicio, ya no tengo más.",
  precio: 10000,
  extension: 24,
  departamento: "San Salvador",
  municipio: "Sivar",
  localidad: "La campanera",
  referencia: "Si",
  usuario: 1235,
  cantimg: 2,
  habita: 1,
  bano: 1,
  garage: 0,
  patio: 0,
};
